name: "Setup Environment"
description: "Sets up Node.js environment and installs dependencies"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: npm
        cache-dependency-path: "package-lock.json"

    # See https://docs.npmjs.com/trusted-publishers
    # Find the latest version with `npm info npm@latest version`
    - name: Install suitable NPM version for trusted publishing
      run: npm install -g npm@11.10.1
      shell: bash
